### ISSUE TITLE
Does this plugin still should work in the lastest elgg version?

### ISSUE THREAD

**Issue by marvson** [hypeJunction/hypeGraph#5]
Hello. I was trying to use this plugin, but I'm having a lot of trouble. Does this plugin still should work in the lastest version of elgg? I know that has been three years, but if it still works it will save me a lot of work.

**Comment by hypeJunction** [comment]
Haven't used it in a a while, but I would expect it to work.

**Comment by hypeJunction** [comment]
Ah, it was written for 1.11, so there are probably issues.

**Comment by marvson** [comment]
After I cleared the cache It started to work properly. It's amazing that this seems to be still working in the 2.3.5 version. That's a amazing job, and thanks for answering. If I find any major issue, I will report and I may fork and try to fix it, if you don't mind.

**Comment by hypeJunction** [comment]
Go for it, that's what github is for.
