### ISSUE TITLE
The API doesn't deal with CORS

### ISSUE THREAD

**Issue by marvson** [hypeJunction/hypeGraph#6]
Since this module is very old, seems like it wasn't necessary when it was created, but now it's necessary dealing with CORS and the 'options' request. I searched in the entire module with a file searching tool and didn't find any 'Access-Control-Allow-Origin'. Because of this, when I try to send a POST requisition to generate a token, the browser denies the request. It works using PostMan, because PostMan is just for testing and ignores CORS. I'm dealing with this issue already.

**Comment by hypeJunction** [comment]
Elgg registers it's CORS handler, look there.

**Comment by marvson** [comment]
That's weird, so it may be something with elgg then, because I had tested and this is working well with PostMan that doesn't uses CORS, but at the browser, I get this:

> Failed to load http://[::1]/sites/elgg/services/api/graph/me/token/: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. The response had HTTP status code 401.

[EDIT]

I still have no idea why it's not only refusing the origin but also the header 'X-Elgg-apikey'. After passing all the day checking elgg's core and your plugin, still no clue.
